# Generated by Django 2.1.5 on 2019-02-21 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Make', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FBID', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=100)),
                ('SchoolEmail', models.EmailField(max_length=254)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('PhoneNum', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('CreationTime', models.DateTimeField()),
                ('SchoolName', models.CharField(max_length=50)),
                ('ProfilePic', models.BinaryField()),
                ('EduVerified', models.BooleanField()),
                ('EduVerifyTime', models.DateTimeField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
