# Generated by Django 2.1.5 on 2019-02-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190221_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Car'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ContactEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='EduVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='EduVerifyTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='FBID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='PhoneNum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ProfilePic',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='SchoolEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='SchoolName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='FullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
