# Generated by Django 2.1.5 on 2019-02-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverequest',
            name='Rider',
        ),
        migrations.DeleteModel(
            name='DriveRequest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
