# Generated by Django 2.1.5 on 2019-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_auto_20190221_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FBID', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=100)),
                ('SchoolEmail', models.EmailField(max_length=254)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('PhoneNum', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('CreationTime', models.DateTimeField()),
                ('SchoolName', models.CharField(max_length=50)),
                ('CarMake', models.CharField(max_length=30)),
                ('CarModel', models.CharField(max_length=30)),
                ('CarYear', models.IntegerField()),
                ('ProfilePic', models.BinaryField()),
                ('EduVerified', models.BooleanField()),
                ('EduVerifyTime', models.DateTimeField()),
            ],
        ),
    ]
