# Generated by Django 2.1.5 on 2019-02-21 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FromLat', models.DecimalField(decimal_places=10, max_digits=15)),
                ('FromLong', models.DecimalField(decimal_places=10, max_digits=15)),
                ('ToLat', models.DecimalField(decimal_places=10, max_digits=15)),
                ('ToLong', models.DecimalField(decimal_places=10, max_digits=15)),
                ('MinDepartTime', models.DateTimeField()),
                ('MaxDepartTime', models.DateTimeField()),
                ('PriceOffer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LuggageSqFt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('RequestTime', models.DateTimeField()),
                ('Completed', models.BooleanField()),
                ('CompleteTime', models.DateTimeField()),
                ('Rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
