# Generated by Django 2.1.7 on 2019-04-17 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Make', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FromLat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('FromLong', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('ToLat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('ToLong', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('MinDepartTime', models.DateTimeField(blank=True, null=True)),
                ('MaxDepartTime', models.DateTimeField(blank=True, null=True)),
                ('PriceOffer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LuggageSqFt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('RequestTime', models.DateTimeField(blank=True, null=True)),
                ('Completed', models.BooleanField(blank=True, null=True)),
                ('CompleteTime', models.DateTimeField(blank=True, null=True)),
                ('departLoc', models.CharField(default='departureLoc', max_length=100)),
                ('arrivalLoc', models.CharField(default='arrivalLoc', max_length=100)),
                ('pickupTime', models.DateTimeField()),
                ('dropTime', models.DateTimeField()),
                ('numOfSeats', models.IntegerField()),
                ('numOfBaggage', models.IntegerField()),
                ('Car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Car')),
                ('Rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('ReviewText', models.CharField(max_length=500)),
                ('Anon', models.BooleanField(blank=True, null=True)),
                ('ReviewTime', models.DateTimeField(blank=True, null=True)),
                ('Reviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee_user', to=settings.AUTH_USER_MODEL)),
                ('Reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiderLink',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Confirmed', models.BooleanField(blank=True, null=True)),
                ('ConfirmTime', models.DateTimeField(blank=True, null=True)),
                ('DriveRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.DriveRequest')),
                ('Rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='Ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.RiderLink'),
        ),
    ]
