# Generated by Django 2.1.7 on 2019-04-02 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('ReviewText', models.CharField(max_length=500)),
                ('Anon', models.BooleanField(blank=True, null=True)),
                ('ReviewTime', models.DateTimeField(blank=True, null=True)),
                ('Reviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee_user', to=settings.AUTH_USER_MODEL)),
                ('Reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
