# Generated by Django 2.1.7 on 2019-04-02 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLink',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Confirmed', models.BooleanField(blank=True, null=True)),
                ('ConfirmTime', models.DateTimeField(blank=True, null=True)),
                ('DriveRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.DriveRequest')),
                ('Rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
