# Generated by Django 2.1.5 on 2019-02-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20190222_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Make', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='driverequest',
            name='Car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Car'),
        ),
    ]
