# Generated by Django 2.1.5 on 2019-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20190417_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderlink',
            old_name='ConfirmTime',
            new_name='ConfirmedTime',
        ),
        migrations.AddField(
            model_name='riderlink',
            name='Denied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderlink',
            name='DeniedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
