# Generated by Django 2.1.7 on 2019-04-18 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20190417_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverequest',
            name='Rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderlink',
            name='Confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='riderlink',
            name='Denied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
