# Generated by Django 2.1.5 on 2019-04-18 02:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20190417_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverequest',
            name='Coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='driverequest',
            name='Rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderlink',
            name='Confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='riderlink',
            name='Denied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
