# Generated by Django 2.1.5 on 2019-04-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20190418_0232'),
        ('driver', '0004_auto_20190418_0254'),
    ]

    operations = [
    ]
