# Generated by Django 2.1.7 on 2019-03-19 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Make', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RiderRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FromLat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('FromLong', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('ToLat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('ToLong', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('MinDepartTime', models.DateTimeField(blank=True, null=True)),
                ('MaxDepartTime', models.DateTimeField(blank=True, null=True)),
                ('PriceOffer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LuggageSqFt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('RequestTime', models.DateTimeField(blank=True, null=True)),
                ('Completed', models.BooleanField(blank=True, null=True)),
                ('CompleteTime', models.DateTimeField(blank=True, null=True)),
                ('departLoc', models.CharField(default='departureLoc', max_length=100)),
                ('arrivalLoc', models.CharField(default='arrivalLoc', max_length=100)),
                ('pickupTime', models.DateTimeField()),
                ('dropTime', models.DateTimeField()),
                ('numOfSeats', models.IntegerField()),
                ('numOfBaggage', models.IntegerField()),
                ('Car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider.Car')),
                ('Rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
